### ISSUE TITLE
Friends/Followers in Author View

### ISSUE THREAD

**Issue by derekdowling** [CMPUT404/socialdistribution#102]
Should be able to toggle between viewing an authors posts and their friends/followers in the author view. Bonus points if you can filter between the two.

**Comment by derekdowling** [comment]
This is going to end up being two lists probably coming in on the author model. "following:[{}], and "friends:[{}]". In both cases there is going to be: { displayName, id, host, url} as objects in each list.

**Comment by xkb** [comment]
Here is a list of ways I think we can do this including what Derek has suggested. 
- Toggle between posts and friends/followers
- Posts, Friends and Followers as tabs?
- Friends/Followers count buttons inside the details header with popup modals?
- Separate page with a fancy grid view?

Feedback?

**Comment by derekdowling** [comment]
I'd say Posts/Friends/Followers tabs where Friends/Followers have a "fancy grid view" is the one I'd like the most. I'm not sure how difficult to implement that would be. I suspect easier than having to rig up a whole new route.

**Comment by lanre-ade** [comment]
I agree, separate tabs makes the most sense considering the user wouldn't want to navigate to a whole different page to see updates

**Comment by derekdowling** [comment]
@KarimBaaba let me know if this can be closed now that #171 is merged when you get the chance.
