### ISSUE TITLE
Image Uploading for Authors/Posts

### ISSUE THREAD

**Issue by derekdowling** [CMPUT404/socialdistribution#103]
We need to add functionality to allow users to upload either as their profile picture or for content they are trying to post.

**Comment by derekdowling** [comment]
@jcairo is currently on the backend for this.

**Comment by xkb** [comment]
Comments as well? I don't think that's supported on the backend.

**Comment by derekdowling** [comment]
You're right. That's not in the spec. Let's just not bother with it.

**Comment by xkb** [comment]
[Jasny's fileinput](http://jasny.github.io/bootstrap/javascript/#fileinput) or [JQuery File Upload](http://blueimp.github.io/jQuery-File-Upload/) for styling?

**Comment by derekdowling** [comment]
Jasny's IMO.

**Comment by derekdowling** [comment]
Closed by #222
