### ISSUE TITLE
Logout Not Redirecting to Login Page

### ISSUE THREAD

**Issue by derekdowling** [CMPUT404/socialdistribution#113]
When I hit logout from the author view, my posts get hidden but I stay there. While this is probably okay, it doesn't feel good from a UX experience. Should either direct you to public posts or to the login screen.

**Comment by xkb** [comment]
This is intentional behaviour to showcase public profiles. We agreed that /author will always work even without auth, so it will be up to the backend to determine what to return which is currently broken for unauthenicated users.

**Comment by derekdowling** [comment]
I think we're probably better off kicking them out of that view to one specified above. Otherwise we're going to make the logout logic pretty convoluted with having to also have the context of what specific page they're on so the backend can re-compute their acls/content that will need to be re-rendered immediately after logout.

**Comment by xkb** [comment]
In theory, no extra front-end work is required as the current user token is removed and the same ajax call that loaded page will be re-fired.... But yes, it is a little of bit of a weird ux.

I'll revisit after public posts.

**Comment by xkb** [comment]
This was fixed in b0f94b18dbc01cc85b871b59d82c74481f08bd9
