### ISSUE TITLE
[EXTRA] Front-end stuff

### ISSUE THREAD

**Issue by xkb** [CMPUT404/socialdistribution#116]
Some extra and unrequired tasks that we can do on the front-end.

Easy:
- [ ] Refactor Spinner into a mixin?
- [ ] contentType for comments
- [x] Markdown/HTML preview tab
- [ ] [Bootstrap-select](http://silviomoreto.github.io/bootstrap-select/) for all select inputs
- [ ] Form validation with [jqBootstrapValidation](http://reactiveraven.github.io/jqBootstrapValidation/)
- [ ] Switch ugly-ish notifcations to [bs-growl](https://github.com/ifightcrime/bootstrap-growl) or [bs-notify](https://github.com/goodybag/bootstrap-notify)

Ughh:
- [x] Derek's usersearch typeahead in navbar with [bootstrap](http://sandglaz.github.io/bootstrap-tagautocomplete/)?
- [ ] Maybe maybe maybe some Store caching?

Everyone feel free to add or take on tasks...

**Comment by derekdowling** [comment]
Closing since we've done most of this in other ways/out of time.
