### ISSUE TITLE
Author Serializer Return Relations

### ISSUE THREAD

**Issue by derekdowling** [CMPUT404/socialdistribution#160]
When getting data from the serializer it should return the following relation fields on successful login:

```
"following": []
"friends": []
"pending": []
"requests": []
```

Each of which is a potentially empty list of CachedAuthors. The models are already hooked up the serializers just need to be dealt with.

**Comment by xkb** [comment]
Another note on this, I'm expecting these fields to be always set and returned via `GET /author/login` and `GET /author/:id`

`pending` and `following` should be empty lists when `GET /author/:id` is on a foreign author or an author that isn't the one making the request. Does that make sense?

**Comment by lanre-ade** [comment]
So basically return friends, following etc only when author is requesting their own information?

**Comment by xkb** [comment]
`friends` should always be returned regardless of requester.

**Comment by derekdowling** [comment]
Closed by #171
