### ISSUE TITLE
pubDate serialization in Post/Comment Serializer

### ISSUE THREAD

**Issue by derekdowling** [CMPUT404/socialdistribution#164]
Ensure everything is up to snuff here. Either make the wacky format in the spec work, or remove comment around it.

**Comment by mraypold** [comment]
I can work on this. Is it going to effect other teams integrations?

**Comment by derekdowling** [comment]
Not sure. Really we just need to look at the spec and figure out if we're close enough. Ideally we'd be using the specs format, but hopefully it's not too crazy to sort out.

**Comment by mraypold** [comment]
I'm currently waiting on clarification from the professor. Current implementation is ISO 8601, which deviates from the specs, but was mentioned in class.

**Comment by mraypold** [comment]
Professor Hindle has confirmed that iso-8601 is the correct format for the pubDate fields. DRF defaults to ISO 8601 when deserializing DateTimeField.
