### ISSUE TITLE
WIKI Documentation

### ISSUE THREAD

**Issue by derekdowling** [CMPUT404/socialdistribution#165]
TODO:
- [x] Fix ACLs page and all refences, should be "FOAF", "PUBLIC", etc
- [x] Fix routes to match spec, all should be in place now, example add missing author ids between `/author/post/:id`
- [ ] routes with posts in them should be using :guid for /post/:guid/comments to match the spec
- [x] Fix Test Overiew Page
- [x] Fix https://github.com/CMPUT404/socialdistribution/wiki/Relationships to be inline with the spec
- [x] add part 2 wiki link
- [x] explicit api page

**Comment by jcairo** [comment]
I'll start working on this now.

**Comment by xkb** [comment]
I believe @mraypold was just working on this

**Comment by mraypold** [comment]
The test overview page is completed. The relationships page is now inline with the specs.

**Comment by mraypold** [comment]
What else did the TA ask for in the project [wiki page](https://github.com/CMPUT404/socialdistribution/wiki/Project-Part-2)?

**Comment by derekdowling** [comment]
As far as I can remember that looks like everything.

**Comment by derekdowling** [comment]
This looks good. Went around adding more API details and making method calls to endpoints more explicit as well.
