### ISSUE TITLE
Incorrect updates to requests/pending lists

### ISSUE THREAD

**Issue by xkb** [CMPUT404/socialdistribution#167]
Author A makes a friend to request author B.

As of right now based on snooping through the admin panel,
Author B is added to A's `requests` list
Nothing changes in the B model.

What should happen...
Author B is added to A's `pending` list
Author A is added to B's `requests` list

Should be an easy fix.

**Comment by derekdowling** [comment]
Most likely a setting problem with the frontend host. This should probably get re-worked a bit to check auth type rather than host.
