### ISSUE TITLE
[BUG] Author post's need to be filtered

### ISSUE THREAD

**Issue by xkb** [CMPUT404/socialdistribution#172]
[Code here](https://github.com/CMPUT404/socialdistribution/blob/master/api/views/content.py#L120]) should be using [djangoobjectpermissionsfilter](http://www.django-rest-framework.org/api-guide/filtering/#djangoobjectpermissionsfilter) or some filtering [like here](https://github.com/CMPUT404/socialdistribution/blob/master/api/views/content.py#L160)

**Comment by derekdowling** [comment]
Closed by #174
