### ISSUE TITLE
Search authors resource

### ISSUE THREAD

**Issue by xkb** [CMPUT404/socialdistribution#189]
I need a call to search all authors we have( remote too ) and return a list.
Don't include posts to avoid dealing with permissions.

Here is a basic scheme that you don't have to follow:
### Request

> GET /authors
### Response

A list of authors via `CachedAuthorSerializer` ?

```
{ "authors": [ ] }
```

**Comment by derekdowling** [comment]
What if we just feed you a list of all authors and you filter on your side?

**Comment by xkb** [comment]
Updated .

**Comment by derekdowling** [comment]
Okay @KarimBaaba this should be working now from the backend side via `GET /authors` including foreign nodes.

**Comment by derekdowling** [comment]
Done.
