### ISSUE TITLE
Breaking bugs and tests

### ISSUE THREAD

**Issue by xkb** [CMPUT404/socialdistribution#201]
- @jcairo: [PR#199](https://github.com/CMPUT404/socialdistribution/pull/199/files#diff-dae704177d06d24712d1afcf2b42efccL34) broke `/authors` by removing the url completely. 
- @derekdowling: [test_api_get_friends](https://github.com/CMPUT404/socialdistribution/blob/master/api/tests/test_follower_api.py#L219) broken because the returned data has the original id hyphenated. 

I'm assuming the rest of integration test failures are still normal?

The hyphenation in CachedAuthor renders the front end completely unusable. Various methods are sending different formats of the same id.

I understand that we need it to get other teams crap working but there must be a better solution.
1. It's broke.
2. If we integrate with another team that doesn't hyphenate.

**Possible Solution**: 
Change the `id` field in `CachedAuthor` to a `CharField`. CachedAuthor instances are only created from existing authors or foreign authors. We don't need auto generation or `UUIDField` formatting.

This would also enable us to integrate with other teams that don't use uuids and as long their ids are unique.

**Comment by jcairo** [comment]
Too many dd's. I added the author URL back in PR 203.

**Comment by derekdowling** [comment]
@KarimBaaba the integration tests only work if we're running their server locally. There are too many conditions that they impose to test against their production server. I think changing the CachedAuthor to a charfield is the best bet.

**Comment by derekdowling** [comment]
This has been since dealt with, thanks for hunting this down @KarimBaaba.
