### ISSUE TITLE
Post's contentType not matching

### ISSUE THREAD

**Issue by xkb** [CMPUT404/socialdistribution#218]
Post Serializer needs to spit out `content-type` instead of `contentType`

@lanre-ade can you get on this or whoever is free?

Confirm with @derekdowling on integration stuff.

**Comment by derekdowling** [comment]
This shouldn't really affect the integrations. I'll double check that they are returning the proper types and if not I'll do it manually.

**Comment by lanre-ade** [comment]
I'll get on it

**Comment by derekdowling** [comment]
Closed by #220
