### ISSUE TITLE
Post "categories"

### ISSUE THREAD

**Issue by xkb** [CMPUT404/socialdistribution#219]
This field doesn't seem to be a requirement (AFAIK) but we have it added it since it appears in `example-article.json`

Do other teams have it as well? Should we remove it or keep it?

If it stays:
- [ ] Add backend test(s) for it
- [ ] Add FE input via `ContentCreator`

**Comment by derekdowling** [comment]
My thought is we shouldn't worry about adding it to the site, but we should provide parsing compatibilities for it.

**Comment by derekdowling** [comment]
Closing since we're not doing this as it's not really in the spec/mandatory.
