### ISSUE TITLE
As an author, posts I create can link to images.

### ISSUE THREAD

**Issue by jcairo** [CMPUT404/socialdistribution#26]

**Comment by derekdowling** [comment]
@jcairo update this to backend complete when you merge your stuff.

**Comment by derekdowling** [comment]
Backend done as part of #123

**Comment by derekdowling** [comment]
This is done.

**Comment by xkb** [comment]
No? Still needs to be hooked up on the front-end

**Comment by derekdowling** [comment]
Whoops, late night. Misread that.
