### ISSUE TITLE
As a server admin, I want to share or not share images with users on other servers.

### ISSUE THREAD

**Issue by jcairo** [CMPUT404/socialdistribution#39]

**Comment by derekdowling** [comment]
@jcairo any idea what might need to happen for this?

**Comment by jcairo** [comment]
Hmmm If we can distinguish between whether a user is a server or an author we should be able to handle this by a check in the view.

**Comment by derekdowling** [comment]
Add to api_settings.settings a NODE_IMAGE_PERMISSION and check in image fetching route if user is Node instance and setting is true or false.

**Comment by derekdowling** [comment]
Closed by #155
