### ISSUE TITLE
As an author, I want to feel safe about sharing images and posts with my friends – images should not publicly accessible without authentication. 

### ISSUE THREAD

**Issue by jcairo** [CMPUT404/socialdistribution#45]

**Comment by derekdowling** [comment]
If the incoming API request doesn't come with an authentication token, do not return an image blob with the post or author profile API responses.

**Comment by mraypold** [comment]
This isn't going to be finished for this milestone. I've replaced it with Issue #49 As a server admin, I want to be able add, modify, and remove authors.

**Comment by derekdowling** [comment]
Related to #103

**Comment by derekdowling** [comment]
@jcairo can this be worked into the serializers as well?

**Comment by jcairo** [comment]
This will be taken care of with a permissions class. It should be the same class as posts for post images. For author images we will have to decide but I assume they could all be public.

**Comment by derekdowling** [comment]
Yeah, I guess it will be dependent on how we implement Node authorization.
