### ISSUE TITLE
As an author, I want un-befriend local and remote authors

### ISSUE THREAD

**Issue by jcairo** [CMPUT404/socialdistribution#46]

**Comment by derekdowling** [comment]
Related to #23. @mraypold any idea of this logic is done in the backend side?

**Comment by derekdowling** [comment]
Hmm, this still needs some work. I guess we just do the same request with a DELETE instead of a post?

**Comment by jcairo** [comment]
Probably the most straightforward way ya. 
How do you want it formatted?

**Comment by jcairo** [comment]
Looks like we already have functionality for this.
https://github.com/CMPUT404/socialdistribution/blob/master/api/views/author.py#L151-L175
https://github.com/CMPUT404/socialdistribution/blob/master/api/tests/test_follower_api.py#L132-L144

**Comment by mraypold** [comment]
Only works for local authors at the moment.

**Comment by xkb** [comment]
Un-friending local/remote is the same thing as the request is local only.
