### ISSUE TITLE
As a server admin, I want to be able allow users to sign up but require my OK to finally be on my server

### ISSUE THREAD

**Issue by jcairo** [CMPUT404/socialdistribution#50]

**Comment by derekdowling** [comment]
@mraypold is this implemented?

**Comment by mraypold** [comment]
No, not implemented fully yet.

**Comment by derekdowling** [comment]
This is almost done. We just need to work on the authentication side and switch "Enabled" in the APIUser model to default to false.

**Comment by derekdowling** [comment]
TODO:
- [x] extend BasicAuth DRF Authentication Class to check "enabled" field on APIUser, "Registration is still pending admin approval."
- [x] return 201 Created on Registration, no data

**Comment by derekdowling** [comment]
Cloed by #151
