### ISSUE TITLE
As an author, other authors cannot modify my data

### ISSUE THREAD

**Issue by jcairo** [CMPUT404/socialdistribution#53]

**Comment by derekdowling** [comment]
So, I mean we can do our best on our end to make sure no inappropriate forms are added, but it's up to you guys to ensure that any author profile update requests made for a given author id correspond to that of their basic auth token.

**Comment by mraypold** [comment]
I'm going to work on this now. We currently do not have an endpoint to update author details.

**Comment by mraypold** [comment]
Editing author profiles is now restricted. Editing comments/posts is not required.
