### ISSUE TITLE
As an author, my server will know about my friends

### ISSUE THREAD

**Issue by jcairo** [CMPUT404/socialdistribution#55]

**Comment by derekdowling** [comment]
@mraypold I'm assigning this one to you. It should hook into the Author serializer so we don't need to make an extra call from the app side. We can set up the extra calls after or as part of closing this.

**Comment by derekdowling** [comment]
@mraypold I think this is done now, right?

**Comment by mraypold** [comment]
Perhaps wait for confirmation on friends/followers from Hindle before closing. Otherwise completed by my interpretation.

**Comment by derekdowling** [comment]
Yup, this is done.
