### ISSUE TITLE
As an author, When I befriend someone it follows them, only when the other authors befriends me do I count as a real friend.

### ISSUE THREAD

**Issue by jcairo** [CMPUT404/socialdistribution#56]

**Comment by derekdowling** [comment]
@KarimBaaba do we want to just handle computing "friends" on the front end based on a returned lists "followers" and "following"? Within the widget?

**Comment by derekdowling** [comment]
Our lives will be a lot easier if we can bake our FriendRelationship logic into /author/:id calls. Then we can have that information pre-calculated for the logged in author. Thoughts @KarimBaaba?

**Comment by xkb** [comment]
Anything we can offload to the front-end I'm cool with as long is it abides by API specs and doesn't violate any privacy concerns.

**Comment by derekdowling** [comment]
This guy is done with #161
