### ISSUE TITLE
As an author, I want to know if I have friend requests.

### ISSUE THREAD

**Issue by jcairo** [CMPUT404/socialdistribution#57]

**Comment by derekdowling** [comment]
This requires stuffing some additional data into the Author model most likely and then popping it when we serve author data for the logged in user.

**Comment by derekdowling** [comment]
@mraypold are you okay with taking this? Since you're fairly intimately familiar with the friending code, this shouldn't be to hard to hook in.

**Comment by mraypold** [comment]
I can take this. There is still some cleanup todo in the friend/follower views prior to this.

**Comment by derekdowling** [comment]
TODO:
- [ ] return requests:[] on successful login

**Comment by derekdowling** [comment]
Closes with #160

**Comment by derekdowling** [comment]
@KarimBaaba is there a way to display friend notifications right now? I'd say it's not crucial to this milestone.

**Comment by xkb** [comment]
No not currently. Haven't decided where to display it.

**Comment by derekdowling** [comment]
I'd argue in the navbar. FB style. But that might be more work. Anyway, it's not crucial for tomorrow.

**Comment by derekdowling** [comment]
@KarimBaaba is this in master yet? I know I saw it yesterday.

**Comment by xkb** [comment]
No, making a PR right now.
